In [2]:
# testando a criação de folds - validação cruzada
# http://scikit-learn.org/stable/modules/cross_validation.html

import numpy as np
from sklearn.utils import shuffle
from sklearn.model_selection import StratifiedKFold

#dados
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9,10],[11,12]])
y = np.array([0, 0, 0, 1, 1, 1])
print ("Dados:")
print ("X = \n" + str(X))
print ("y = \n" + str(y))
print (" ")

# embaralha a matriz de dados e as classes ao mesmo tempo
xEmbaralhado, yEmbaralhado = shuffle(X, y, random_state=5)
print("Dados embaralhados:")
print ("X = \n" + str(xEmbaralhado))
print ("y = \n" + str(yEmbaralhado))
print (" ")

skf = StratifiedKFold(3)
print("Folds:")
print(skf)  
print (" ")

i = 0
for indicetreino, indiceteste in skf.split(xEmbaralhado,yEmbaralhado):
    i = i + 1
    print ("-------------------------------------------------- ")
    print ("Fold " + str(i))
    print ("indice treino = " + str(indicetreino) + ", indice teste = " + str(indiceteste))
    print ("dados treino = \n" + str(xEmbaralhado[indicetreino]))
    print (" ")
    print ("dados teste = \n" + str(yEmbaralhado[indiceteste]))
   


Dados:
X = 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
y = 
[0 0 0 1 1 1]
 
Dados embaralhados:
X = 
[[11 12]
 [ 5  6]
 [ 9 10]
 [ 3  4]
 [ 1  2]
 [ 7  8]]
y = 
[1 0 1 0 0 1]
 
Folds:
StratifiedKFold(n_splits=3, random_state=None, shuffle=False)
 
-------------------------------------------------- 
Fold 1
indice treino = [2 3 4 5], indice teste = [0 1]
dados treino = 
[[ 9 10]
 [ 3  4]
 [ 1  2]
 [ 7  8]]
 
dados teste = 
[1 0]
-------------------------------------------------- 
Fold 2
indice treino = [0 1 4 5], indice teste = [2 3]
dados treino = 
[[11 12]
 [ 5  6]
 [ 1  2]
 [ 7  8]]
 
dados teste = 
[1 0]
-------------------------------------------------- 
Fold 3
indice treino = [0 1 2 3], indice teste = [4 5]
dados treino = 
[[11 12]
 [ 5  6]
 [ 9 10]
 [ 3  4]]
 
dados teste = 
[0 1]
